# Generated by Django 5.2.4 on 2025-08-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Lock agent to prevent modifications"
            ),
        ),
    ]
